sessions:
  - prefix: http://nuc/munin
    setup:
      - localdomain/index.html
    urls:
      - localdomain/index.html
      - localdomain/localhost.localdomain/diskstats_iops/index.html
    max-parallel-requests: 1
    timings:
      resolution: 240
      period: 3600
      span: 10
  - prefix: http://nuc
    urls:
      - ''
  - prefix: http://localhost:8080
    urls:
      - 1
      - 2
      - 3
      - 4
mode: async